export type DirectoryStation = {
  id: number;
  stationName: string;
  address: string;
  googleMapsUrl: string;
  fuelType?: string;
};

function mapsUrl(name: string, address: string) {
  return `https://www.google.com/maps/search/${encodeURIComponent(name + " " + address)}`;
}

export const stationsDirectory: DirectoryStation[] = [
  { id: 1, stationName: "Amin Petrol Pump", address: "Secretariat Road, Dhaka", googleMapsUrl: mapsUrl("Amin Petrol Pump", "Secretariat Road Dhaka"), fuelType: "Petrol" },
  { id: 2, stationName: "A Hye & Co", address: "Hatkhola Road, Dhaka", googleMapsUrl: mapsUrl("A Hye & Co", "Hatkhola Road Dhaka"), fuelType: "Petrol" },
  { id: 3, stationName: "Green View Petrol Pump", address: "Green Road, Dhaka", googleMapsUrl: mapsUrl("Green View Petrol Pump", "Green Road Dhaka"), fuelType: "Petrol" },
  { id: 4, stationName: "L Rahman & Osman Ghani & Sons", address: "Mymensingh Road, Dhaka", googleMapsUrl: mapsUrl("L Rahman & Osman Ghani & Sons", "Mymensingh Road Dhaka"), fuelType: "Petrol" },
  { id: 5, stationName: "M Azim Zulfiquar & Sons", address: "Karwan Bazar, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("M Azim Zulfiquar & Sons", "Karwan Bazar Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 6, stationName: "Mainuddin Akhtaruddin Chowdhury", address: "159 Bajekakrail, Dhaka", googleMapsUrl: mapsUrl("Mainuddin Akhtaruddin Chowdhury", "159 Bajekakrail Dhaka"), fuelType: "Petrol" },
  { id: 7, stationName: "Margarett & Sons", address: "17 Airport Road, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Margarett & Sons", "17 Airport Road Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 8, stationName: "Polwel Filling Station", address: "Police Welfare Trust, Mill Barrack, Dhaka", googleMapsUrl: mapsUrl("Polwel Filling Station", "Police Welfare Trust Mill Barrack Dhaka"), fuelType: "Petrol" },
  { id: 9, stationName: "Aziz Corporation", address: "36 Dilkusha C/A, Dhaka", googleMapsUrl: mapsUrl("Aziz Corporation", "36 Dilkusha CA Dhaka"), fuelType: "Petrol" },
  { id: 10, stationName: "PWD Sports Club Filling Station", address: "Asad Gate, Dhaka", googleMapsUrl: mapsUrl("PWD Sports Club Filling Station", "Asad Gate Dhaka"), fuelType: "Petrol" },
  { id: 11, stationName: "Mirpur Petrol Pump", address: "3 Jikatuli, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Mirpur Petrol Pump", "3 Jikatuli Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 12, stationName: "Kurmitola Petrol Pump", address: "Dhaka Cantonment, Dhaka", googleMapsUrl: mapsUrl("Kurmitola Petrol Pump", "Dhaka Cantonment Dhaka"), fuelType: "Petrol" },
  { id: 13, stationName: "Gulshan Autos", address: "Gulshan, Dhaka", googleMapsUrl: mapsUrl("Gulshan Autos", "Gulshan Dhaka"), fuelType: "Petrol" },
  { id: 14, stationName: "Joydebpur Filling Station", address: "Joydebpur, Dhaka", googleMapsUrl: mapsUrl("Joydebpur Filling Station", "Joydebpur Dhaka"), fuelType: "Petrol" },
  { id: 15, stationName: "Malibagh Auto Service", address: "Malibagh, Dhaka", googleMapsUrl: mapsUrl("Malibagh Auto Service", "Malibagh Dhaka"), fuelType: "Petrol" },
  { id: 16, stationName: "Mouchak Boyscout Filling Station", address: "Mouchak, Dhaka", googleMapsUrl: mapsUrl("Mouchak Boyscout Filling Station", "Mouchak Dhaka"), fuelType: "Petrol" },
  { id: 17, stationName: "Pubali Traders", address: "Road 30, House 708, Dhanmondi, Dhaka", googleMapsUrl: mapsUrl("Pubali Traders", "Road 30 House 708 Dhanmondi Dhaka"), fuelType: "Petrol" },
  { id: 18, stationName: "Pather Bandhu", address: "New Market, Dhaka", googleMapsUrl: mapsUrl("Pather Bandhu", "New Market Dhaka"), fuelType: "Petrol" },
  { id: 19, stationName: "Purbachal Traders", address: "Mymensingh Road, Paribagh, Dhaka", googleMapsUrl: mapsUrl("Purbachal Traders", "Mymensingh Road Paribagh Dhaka"), fuelType: "Petrol" },
  { id: 20, stationName: "Rupali Filling Station", address: "29 Kalicharan Saha Road, Dhaka", googleMapsUrl: mapsUrl("Rupali Filling Station", "29 Kalicharan Saha Road Dhaka"), fuelType: "Petrol" },
  { id: 21, stationName: "Abdur Rahman Pathik", address: "166 Nawabpur Road, Dhaka", googleMapsUrl: mapsUrl("Abdur Rahman Pathik", "166 Nawabpur Road Dhaka"), fuelType: "Petrol" },
  { id: 22, stationName: "Sharathi", address: "13 Syed Golam Mostafa Lane, Dhaka", googleMapsUrl: mapsUrl("Sharathi", "13 Syed Golam Mostafa Lane Dhaka"), fuelType: "Petrol" },
  { id: 23, stationName: "Ramna Filling Station", address: "21 Dhanmondi, Dhaka", googleMapsUrl: mapsUrl("Ramna Filling Station", "21 Dhanmondi Dhaka"), fuelType: "Petrol" },
  { id: 24, stationName: "Shohag Filling Station", address: "Hashmat Ali, Dhaka", googleMapsUrl: mapsUrl("Shohag Filling Station", "Hashmat Ali Dhaka"), fuelType: "Petrol" },
  { id: 25, stationName: "M Akhtar Hossain", address: "Jatrabari, Dhaka", googleMapsUrl: mapsUrl("M Akhtar Hossain", "Jatrabari Dhaka"), fuelType: "Petrol" },
  { id: 26, stationName: "Bengal International Agency", address: "Dhanmondi, Dhaka", googleMapsUrl: mapsUrl("Bengal International Agency", "Dhanmondi Dhaka"), fuelType: "Petrol" },
  { id: 27, stationName: "Satata & Co", address: "Mohammadpur, Dhaka", googleMapsUrl: mapsUrl("Satata & Co", "Mohammadpur Dhaka"), fuelType: "Petrol" },
  { id: 28, stationName: "Nessa & Sons", address: "Mirpur, Dhaka", googleMapsUrl: mapsUrl("Nessa & Sons", "Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 29, stationName: "Eastern Filling Station", address: "Allenbari, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Eastern Filling Station", "Allenbari Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 30, stationName: "Sarwar Filling Station", address: "Amin Bazar, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Sarwar Filling Station", "Amin Bazar Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 31, stationName: "Paltan Service Station", address: "61 Purana Paltan, Dhaka", googleMapsUrl: mapsUrl("Paltan Service Station", "61 Purana Paltan Dhaka"), fuelType: "Petrol" },
  { id: 32, stationName: "BD Police Co-Operative", address: "Inner Circular Road, Naya Paltan, Dhaka", googleMapsUrl: mapsUrl("BD Police Co-Operative", "Inner Circular Road Naya Paltan Dhaka"), fuelType: "Petrol" },
  { id: 33, stationName: "SN Enterprise", address: "4 Hossainee Dalan Road, Dhaka", googleMapsUrl: mapsUrl("SN Enterprise", "4 Hossainee Dalan Road Dhaka"), fuelType: "Petrol" },
  { id: 34, stationName: "Kurmitola Filling Station", address: "Kurmitola, Dhaka", googleMapsUrl: mapsUrl("Kurmitola Filling Station", "Kurmitola Dhaka"), fuelType: "Petrol" },
  { id: 35, stationName: "Khan & Chowdhury", address: "Poldar Road, Mathnail, Dhaka", googleMapsUrl: mapsUrl("Khan & Chowdhury", "Poldar Road Mathnail Dhaka"), fuelType: "Petrol" },
  { id: 36, stationName: "Abdullah Filling Station", address: "Jurain, Dhaka", googleMapsUrl: mapsUrl("Abdullah Filling Station", "Jurain Dhaka"), fuelType: "Petrol" },
  { id: 37, stationName: "Kafiluddin Filling Station", address: "Hemayatpur, Savar, Dhaka", googleMapsUrl: mapsUrl("Kafiluddin Filling Station", "Hemayatpur Savar Dhaka"), fuelType: "Petrol" },
  { id: 38, stationName: "Labani Enterprise", address: "18 Lalmoni Street, Wari, Dhaka", googleMapsUrl: mapsUrl("Labani Enterprise", "18 Lalmoni Street Wari Dhaka"), fuelType: "Petrol" },
  { id: 39, stationName: "A Hye & Co (Poldar)", address: "Poldar Road, Dhaka", googleMapsUrl: mapsUrl("A Hye & Co", "Poldar Road Dhaka"), fuelType: "Petrol" },
  { id: 40, stationName: "ABH Enterprise", address: "120/3A Dhaka", googleMapsUrl: mapsUrl("ABH Enterprise", "120 3A Dhaka"), fuelType: "Petrol" },
  { id: 41, stationName: "Denso Filling Station", address: "Gulshan, Dhaka", googleMapsUrl: mapsUrl("Denso Filling Station", "Gulshan Dhaka"), fuelType: "Petrol" },
  { id: 42, stationName: "Gulshan Autos (Raza Bazar)", address: "17 East Raza Bazar, Dhaka", googleMapsUrl: mapsUrl("Gulshan Autos", "17 East Raza Bazar Dhaka"), fuelType: "Petrol" },
  { id: 43, stationName: "Mehera Filling Station", address: "Mohakhali, Dhaka", googleMapsUrl: mapsUrl("Mehera Filling Station", "Mohakhali Dhaka"), fuelType: "Petrol" },
  { id: 44, stationName: "Aman Enterprise", address: "6 Patuatoli Lane, Dhaka", googleMapsUrl: mapsUrl("Aman Enterprise", "6 Patuatoli Lane Dhaka"), fuelType: "Petrol" },
  { id: 45, stationName: "Chowdhury & Associates", address: "Darussalam Road, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Chowdhury & Associates", "Darussalam Road Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 46, stationName: "Denso Filling Station (Savar)", address: "Nabinagar, Savar, Dhaka", googleMapsUrl: mapsUrl("Denso Filling Station", "Nabinagar Savar Dhaka"), fuelType: "Petrol" },
  { id: 47, stationName: "Aziz Filling Station", address: "Old Airport Road, Dhaka", googleMapsUrl: mapsUrl("Aziz Filling Station", "Old Airport Road Dhaka"), fuelType: "Petrol" },
  { id: 48, stationName: "Eastern Filling Station (Kabirpur)", address: "Kabirpur, Dhaka", googleMapsUrl: mapsUrl("Eastern Filling Station", "Kabirpur Dhaka"), fuelType: "Petrol" },
  { id: 49, stationName: "Gumati Filling Station", address: "Jatrabari, Dhaka", googleMapsUrl: mapsUrl("Gumati Filling Station", "Jatrabari Dhaka"), fuelType: "Petrol" },
  { id: 50, stationName: "Gani Filling Station", address: "21 Avenue, Uttara, Dhaka", googleMapsUrl: mapsUrl("Gani Filling Station", "21 Avenue Uttara Dhaka"), fuelType: "Petrol" },
  { id: 51, stationName: "Khakon Filling Station", address: "College Road, Auchpara, Dhaka", googleMapsUrl: mapsUrl("Khakon Filling Station", "College Road Auchpara Dhaka"), fuelType: "Petrol" },
  { id: 52, stationName: "Nadi Filling Station", address: "Jirabo, Savar, Dhaka", googleMapsUrl: mapsUrl("Nadi Filling Station", "Jirabo Savar Dhaka"), fuelType: "Petrol" },
  { id: 53, stationName: "Anwara Filling Station", address: "Baghoir, Maowa Road, Dhaka", googleMapsUrl: mapsUrl("Anwara Filling Station", "Baghoir Maowa Road Dhaka"), fuelType: "Petrol" },
  { id: 54, stationName: "Ovi Filling Station", address: "Turag, Amin Bazar, Dhaka", googleMapsUrl: mapsUrl("Ovi Filling Station", "Turag Amin Bazar Dhaka"), fuelType: "Petrol" },
  { id: 55, stationName: "Khaleque Service Station", address: "Darussalam, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Khaleque Service Station", "Darussalam Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 56, stationName: "AS Filling Station", address: "Rokeya Sarani, Kafrul, Dhaka", googleMapsUrl: mapsUrl("AS Filling Station", "Rokeya Sarani Kafrul Dhaka"), fuelType: "Petrol" },
  { id: 57, stationName: "Amtali Filling Station", address: "House 22, Road 4, Dhanmondi, Dhaka", googleMapsUrl: mapsUrl("Amtali Filling Station", "House 22 Road 4 Dhanmondi Dhaka"), fuelType: "Petrol" },
  { id: 58, stationName: "Dewan Filling Station", address: "Norshinghapur, Savar, Dhaka", googleMapsUrl: mapsUrl("Dewan Filling Station", "Norshinghapur Savar Dhaka"), fuelType: "Petrol" },
  { id: 59, stationName: "Sams Filling Station", address: "Mahmud Hossain, Dhaka", googleMapsUrl: mapsUrl("Sams Filling Station", "Mahmud Hossain Dhaka"), fuelType: "Petrol" },
  { id: 60, stationName: "Shahadat Ganio Station", address: "Sector 4, Uttara, Dhaka", googleMapsUrl: mapsUrl("Shahadat Ganio Station", "Sector 4 Uttara Dhaka"), fuelType: "Petrol" },
  { id: 61, stationName: "Cosmo Filling Station", address: "Uttara, Dhaka", googleMapsUrl: mapsUrl("Cosmo Filling Station", "Uttara Dhaka"), fuelType: "Petrol" },
  { id: 62, stationName: "Pubali Filling Station", address: "79A Motijheel, Dhaka", googleMapsUrl: mapsUrl("Pubali Filling Station", "79A Motijheel Dhaka"), fuelType: "Petrol" },
  { id: 63, stationName: "Haq Filling Station", address: "House 43, Road 4, Uttara, Dhaka", googleMapsUrl: mapsUrl("Haq Filling Station", "House 43 Road 4 Uttara Dhaka"), fuelType: "Petrol" },
  { id: 64, stationName: "Gumati Service Centre", address: "South Jatrabari, Dhaka", googleMapsUrl: mapsUrl("Gumati Service Centre", "South Jatrabari Dhaka"), fuelType: "Petrol" },
  { id: 65, stationName: "Sadeque Service Station", address: "Rayer Bazar, Dhaka", googleMapsUrl: mapsUrl("Sadeque Service Station", "Rayer Bazar Dhaka"), fuelType: "Petrol" },
  { id: 66, stationName: "Uttara Filling Station", address: "87 Motijheel, Dhaka", googleMapsUrl: mapsUrl("Uttara Filling Station", "87 Motijheel Dhaka"), fuelType: "Petrol" },
  { id: 67, stationName: "Ideal Filling Station", address: "191 Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Ideal Filling Station", "191 Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 68, stationName: "Trust Filling Station (Cantonment)", address: "Allenbari, Cantonment, Dhaka", googleMapsUrl: mapsUrl("Trust Filling Station", "Allenbari Cantonment Dhaka"), fuelType: "Petrol" },
  { id: 69, stationName: "Confidence Filling Station", address: "Old Secretariate Road, Chankharpool, Dhaka", googleMapsUrl: mapsUrl("Confidence Filling Station", "Old Secretariate Road Chankharpool Dhaka"), fuelType: "Petrol" },
  { id: 70, stationName: "Rashed Rimi Station", address: "62/2 Agargaon, Dhaka", googleMapsUrl: mapsUrl("Rashed Rimi Station", "62 2 Agargaon Dhaka"), fuelType: "Petrol" },
  { id: 71, stationName: "Shahara Station", address: "68/3 Jigatola, Dhaka", googleMapsUrl: mapsUrl("Shahara Station", "68 3 Jigatola Dhaka"), fuelType: "Petrol" },
  { id: 72, stationName: "Shwadhin Bangla", address: "Dhaka", googleMapsUrl: mapsUrl("Shwadhin Bangla", "Dhaka"), fuelType: "Petrol" },
  { id: 73, stationName: "Dighanta Filling Station", address: "Dhaka", googleMapsUrl: mapsUrl("Dighanta Filling Station", "Dhaka"), fuelType: "Petrol" },
  { id: 74, stationName: "SHS Filling Station", address: "473C Khilgaon, Dhaka", googleMapsUrl: mapsUrl("SHS Filling Station", "473C Khilgaon Dhaka"), fuelType: "Petrol" },
  { id: 75, stationName: "Pathan Filling Station", address: "Dhaka", googleMapsUrl: mapsUrl("Pathan Filling Station", "Dhaka"), fuelType: "Petrol" },
  { id: 76, stationName: "Tahsin Enterprise", address: "6A Segunbagicha, Dhaka", googleMapsUrl: mapsUrl("Tahsin Enterprise", "6A Segunbagicha Dhaka"), fuelType: "Petrol" },
  { id: 77, stationName: "Mollah Service Centre", address: "28 Market Road, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Mollah Service Centre", "28 Market Road Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 78, stationName: "Shahjalal Gas Station", address: "Shantinagar, Dhaka", googleMapsUrl: mapsUrl("Shahjalal Gas Station", "Shantinagar Dhaka"), fuelType: "CNG" },
  { id: 79, stationName: "GF Trading", address: "Arjatpara, Mohakhali, Dhaka", googleMapsUrl: mapsUrl("GF Trading", "Arjatpara Mohakhali Dhaka"), fuelType: "CNG" },
  { id: 80, stationName: "Makka CNG Refueling", address: "North Badda, Dhaka", googleMapsUrl: mapsUrl("Makka CNG Refueling", "North Badda Dhaka"), fuelType: "CNG" },
  { id: 81, stationName: "City Filling Station", address: "Distillery Road, Gandaria, Dhaka", googleMapsUrl: mapsUrl("City Filling Station", "Distillery Road Gandaria Dhaka"), fuelType: "Petrol" },
  { id: 82, stationName: "Kamal Trading Agency", address: "Shahid Tajuddin Road, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Kamal Trading Agency", "Shahid Tajuddin Road Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 83, stationName: "Rana International Station", address: "Dhaka Housing, Shyamoly, Dhaka", googleMapsUrl: mapsUrl("Rana International Station", "Dhaka Housing Shyamoly Dhaka"), fuelType: "Petrol" },
  { id: 84, stationName: "Dhaka CNG Fuel Co", address: "Kuratoli, Badda, Dhaka", googleMapsUrl: mapsUrl("Dhaka CNG Fuel Co", "Kuratoli Badda Dhaka"), fuelType: "CNG" },
  { id: 85, stationName: "Borak Service Centre", address: "Nawabpur Road, Dhaka", googleMapsUrl: mapsUrl("Borak Service Centre", "Nawabpur Road Dhaka"), fuelType: "Petrol" },
  { id: 86, stationName: "Purbachal Gas Station", address: "Darussalam Road, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Purbachal Gas Station", "Darussalam Road Mirpur Dhaka"), fuelType: "CNG" },
  { id: 87, stationName: "Trade Consortium", address: "Gabtoli, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Trade Consortium", "Gabtoli Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 88, stationName: "Trust SKS CNG Station", address: "Airport Road, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Trust SKS CNG Station", "Airport Road Tejgaon Dhaka"), fuelType: "CNG" },
  { id: 89, stationName: "Jahanara Filling Station", address: "Dhamrai, Dhaka", googleMapsUrl: mapsUrl("Jahanara Filling Station", "Dhamrai Dhaka"), fuelType: "Petrol" },
  { id: 90, stationName: "Clean Fuel Filling Station", address: "Shahid Tajuddin Road, Tejgaon, Dhaka", googleMapsUrl: mapsUrl("Clean Fuel Filling Station", "Shahid Tajuddin Road Tejgaon Dhaka"), fuelType: "Petrol" },
  { id: 91, stationName: "S Ahmed Foundation Station", address: "Jurain, Shyampur, Dhaka", googleMapsUrl: mapsUrl("S Ahmed Foundation Station", "Jurain Shyampur Dhaka"), fuelType: "CNG" },
  { id: 92, stationName: "Paul CNG Ltd", address: "Dhamrai, Dhaka", googleMapsUrl: mapsUrl("Paul CNG Ltd", "Dhamrai Dhaka"), fuelType: "CNG" },
  { id: 93, stationName: "SP Filling Station", address: "Gabtali, Mirpur, Dhaka", googleMapsUrl: mapsUrl("SP Filling Station", "Gabtali Mirpur Dhaka"), fuelType: "Petrol" },
  { id: 94, stationName: "Comport Filling Station", address: "Kallyanpur, Mirpur, Dhaka", googleMapsUrl: mapsUrl("Comport Filling Station", "Kallyanpur Mirpur Dhaka"), fuelType: "CNG" },
  { id: 95, stationName: "Anwar CNG Service", address: "Ashulia, Savar, Dhaka", googleMapsUrl: mapsUrl("Anwar CNG Service", "Ashulia Savar Dhaka"), fuelType: "CNG" },
];
